server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
#    include-stacktrace: ALWAYS
    include-exception: true

logging:
  level:
    root: INFO
#    com.camptocamp: INFO
    com.camptocamp: TRACE
    reactor.netty.http.client: TRACE
    org.springframework: DEBUG
