---
name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    name: Continuous Integration

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "STATUS: Failure."
      - run: echo "STATUS: Success."
      - run: echo "STATUS: Failure."

