---
name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    name: Continuous Integration

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fail more or less
        run: "false"
        continue-on-error: true

      - name: OnFailure
        run: "echo STATUS: Failure."
        if: failure()

      - name: OnSuccess
        run: "echo STATUS: Success."
        if: success()

      - name: OnAlways
        run: "echo STATUS: Always."
        if: always()

      - name: Try printing a warning
        run: "echo ::warning file=foo.bar,line=1,col=5,endColumn=7::Missing semicolon" 

      - name: Prepare PATH
        run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
        
      - name: Install c2cciutils
        run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks
