---
name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

env:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    name: Continuous Integration

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fail
        run: "false"

      - name: OnFailure
        run: echo "STATUS: Failure."
        if: failure()

      - name: OnSuccess
        run: echo "STATUS: Success."
        if: success()
 
      - name: OnAlways
        run: echo "STATUS: Always."
        if: always()
